# 'brew'
brew "mas"
brew "rcm"
brew "gh"
brew "k6"
brew "sidekick"
brew "tmux"

# 'cask'
cask "raycast"
cask "iterm2"
cask "1password"
cask "flux"
cask "spotify"
cask "mullvadvpn"
cask "zoom"
cask "rapidapi"
